### ISSUE TITLE
Don't write to the artifacts dir

### ISSUE THREAD

**Issue by maleadt** [gaelforget/OceanStateEstimation.jl#40]
This package seems to write to the directory of the `ECCOclim` artifact, as there's a `ETAN` file that appears after running the test suite. This isn't great; the artifacts store should be immutable (as it's content-addressable), so any mutation prevents e.g. PkgEval from caching artifacts.

**Comment by gaelforget** [comment]
Should be fixed with `v0.2.10`. Thank you!
