### ISSUE TITLE
Consider using Artifacts for data

### ISSUE THREAD

**Issue by vchuravy** [gaelforget/OceanStateEstimation.jl#6]
PackageEvaluator.jl runs nightly tests over the package ecosystem and looking at our traffic numbers I noticed that `IndividualDisplacements` downloads 1.747GB of data during it's tests. Using Artifacts.jl would allow us to cache that.

**Comment by gaelforget** [comment]
Hopefully what I did in https://github.com/gaelforget/OceanStateEstimation.jl/pull/8 will be helpful.

Looking into Artifacts for this had been on my to do list. Thanks for bringing it up. 

Not sure I totally understand how best to handle my use case though (many files, downloaded from DOI'ed archive, not in tar ball, downloaded by parts). I feel that what I did is a bit of a hack but it seems to work ok. Will try using this in IndividualDisplacements after new release is completed

**Comment by vchuravy** [comment]
Thanks!

**Comment by gaelforget** [comment]
I think I finished moving data dependencies to the Artifacts system as of v0.2.1 of IndividualDisplacements.jl (released 5 days ago). 

Some of the downloads associated with the artifacts still happen _manually_  but at least they go to `~/.Julia/artifacts`

Am wondering how much of an impact this had on the PackageEvaluator.jl runs -- could you please check @vchuravy when you get a chance?

**Comment by vchuravy** [comment]
Looks better: https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_date/2020-11/10/OceanStateEstimation.1.6.0-DEV-9c498bff43.log 

```
Network usage:
- eth0: 126.608 MiB received, 708.351 KiB sent
```
